// constants.ts
import { 
  Type, 
  FileText, 
  Mail, 
  Hash, 
  Calendar, 
  ChevronDown, 
  Circle, 
  CheckSquare, 
  Upload, 
  Send,
  Clock,
  Globe,
  Phone,
  Lock,
  Palette,
  Sliders,
  Image,
  Video,
  Volume2,
  Table,
  Star,
  PenTool,
  MapPin,
  CreditCard,
  MousePointer,
  Link,
  Minus,
  Code,
  Calculator,
  Folder,
  BarChart3,
  List,
  Grid,
  Target,
  ExternalLink,
  QrCode,
  PieChart,
  Heading1,
  AlignLeft,
  ToggleLeft,
  Calendar as CalendarIcon,
  Box,
  Layers,
  Move,
  CheckCircle
} from 'lucide-react';

import { ComponentPaletteItem } from './types';

export const DEFAULT_COLORS = [
  '#3b82f6', '#ef4444', '#10b981', '#f59e0b', 
  '#8b5cf6', '#ec4899', '#6b7280', '#000000',
  '#ffffff', '#f3f4f6', '#ddd6fe', '#fef3c7',
  '#dcfce7', '#fee2e2', '#dbeafe', '#f3e8ff'
];

export const COMPONENT_PALETTE_ITEMS: ComponentPaletteItem[] = [
  Kanban,
  Board,
  Card,
  Sticky,
  Note as NoteIcon,
  Notebook,
  Journal,
  Diary,
  Book,
  Library,
  Bookshelf,
  Bookmark as BookmarkSymbol,
  Page,
  Pages,
  Chapter,
  Paragraph,
  Text,
  Font,
  Typography,
  Heading,
  Title,
  Subtitle,
  Quote,
  Blockquote,
  Code as CodeIcon,
  CodeBlock,
  Terminal,
  Console,
  Shell,
  Command,
  Script,
  Function,
  Variable,
  Constant,
  Class,
  Object,
  Array,
  String,
  Number,
  Boolean,
  Null,
  Undefined,
  Json,
  Xml,
  Html,
  Css,
  Javascript,
  Typescript,
  React,
  Vue,
  Angular,
  Svelte,
  Node,
  Npm,
  Yarn,
  Webpack,
  Babel,
  Eslint,
  Prettier,
  Jest,
  Cypress,
  Playwright,
  Selenium,
  Docker,
  Kubernetes,
  Aws,
  Azure,
  Gcp,
  Firebase,
  Supabase,
  Netlify,
  Vercel,
  Heroku,
  Digital,
  Ocean,
  Linode,
  Vultr,
  Cloudflare,
  Github,
  Gitlab,
  Bitbucket,
  Git,
  Branch,
  Commit,
  Push,
  Pull,
  Merge,
  Rebase,
  Stash,
  Tag as GitTag,
  Release,
  Version,
  Semver,
  Changelog,
  Readme,
  License,
  Contributing,
  Issue,
  Bug,
  Feature,
  Enhancement,
  Documentation,
  Wiki,
  Faq,
  Guide,
  Tutorial,
  Example,
  Demo,
  Sandbox,
  Playground,
  Experiment,
  Lab,
  Test,
  Spec,
  Mock,
  Stub,
  Fake,
  Fixture,
  Snapshot,
  Coverage,
  Report,
  Metrics,
  Analytics,
  Insights,
  Dashboard,
  Widget,
  Component,
  Element,
  Fragment,
  Template,
  Layout as LayoutIcon,
  Theme,
  Style,
  Design,
  Pattern,
  Texture,
  Gradient,
  Shadow,
  Border,
  Outline,
  Fill,
  Stroke,
  Color,
  Palette as PaletteSymbol,
  Picker,
  Swatches,
  Hsl,
  Rgb,
  Hex,
  Cmyk,
  Lab,
  Xyz,
  Oklab,
  Oklch,
  P3,
  Rec2020,
  Prophoto,
  Adobe,
  Srgb,
  Gamma,
  Exposure,
  Highlights,
  Shadows,
  Whites,
  Blacks,
  Clarity,
  Vibrance,
  Saturation as SaturationIcon,
  Temperature,
  Tint,
  Split,
  Tone,
  Curve,
  Histogram,
  Levels,
  Threshold,
  Posterize as PosterizeIcon,
  Solarize,
  Equalize,
  Normalize,
  Desaturate,
  Monochrome,
  Duotone,
  Tritone,
  Quadtone,
  Sepia as SepiaIcon,
  Vintage,
  Retro,
  Classic,
  Modern,
  Minimal,
  Elegant,
  Bold,
  Playful,
  Professional,
  Creative,
  Artistic,
  Abstract,
  Geometric,
  Organic,
  Natural,
  Urban,
  Industrial,
  Rustic,
  Luxury,
  Premium,
  Budget,
  Affordable,
  Cheap,
  Expensive,
  Free,
  Paid,
  Subscription,
  License as LicenseIcon,
  Royalty,
  Copyright,
  Trademark,
  Patent,
  Intellectual,
  Property,
  Legal,
  Terms,
  Conditions,
  Privacy,
  Policy,
  Gdpr,
  Ccpa,
  Hipaa,
  Compliance,
  Audit,
  Review,
  Approval,
  Rejection,
  Pending,
  Processing,
  Complete,
  Incomplete,
  Success,
  Failure,
  Error,
  Warning,
  Info as Information,
  Debug,
  Trace,
  Log,
  Event,
  Action,
  Trigger,
  Handler,
  Listener,
  Observer,
  Subscriber,
  Publisher,
  Emitter,
  Dispatcher,
  Queue as QueueIcon,
  Stack,
  Heap,
  Memory,
  Cache,
  Buffer,
  Stream,
  Pipe,
  Filter as FilterIcon,
  Map as MapIcon,
  Reduce,
  Sort,
  Group,
  Aggregate,
  Sum,
  Average,
  Median,
  Mode,
  Min,
  Max,
  Range,
  Variance,
  Deviation,
  Correlation,
  Regression,
  Trend,
  Forecast,
  Predict,
  Classify,
  Cluster,
  Segment,
  Cohort,
  Funnel,
  Conversion,
  Retention,
  Churn,
  Ltv,
  Cac,
  Roi,
  Kpi,
  Metric,
  Dimension,
  Measure,
  Fact,
  Dimension as DimensionIcon,
  Cube,
  Olap,
  Oltp,
  Etl,
  Elt,
  Pipeline,
  Workflow as WorkflowIcon,
  Process,
  Procedure,
  Algorithm,
  Logic,
  Condition,
  Branch,
  Loop,
  Iteration,
  Recursion,
  Sequence,
  Parallel,
  Concurrent,
  Async,
  Await,
  Promise,
  Callback,
  Event as EventIcon,
  Listener as ListenerIcon,
  Hook,
  Middleware,
  Interceptor,
  Decorator,
  Wrapper,
  Adapter,
  Facade,
  Proxy,
  Singleton,
  Factory,
  Builder,
  Strategy,
  Observer as ObserverIcon,
  Command as CommandIcon,
  State,
  Mediator,
  Chain,
  Responsibility,
  Visitor,
  Iterator,
  Composite,
  Flyweight,
  Bridge,
  Prototype,
  Abstract,
  Concrete,
  Interface,
  Implementation,
  Inheritance,
  Composition,
  Aggregation,
  Association,
  Dependency,
  Coupling,
  Cohesion,
  Encapsulation,
  Abstraction,
  Polymorphism,
  Overloading,
  Overriding,
  Hiding,
  Binding,
  Resolution,
  Dispatch,
  Invocation,
  Execution,
  Runtime,
  Compile,
  Interpret,
  Transpile,
  Optimize,
  Minify,
  Uglify,
  Obfuscate,
  Bundle,
  Split,
  Chunk,
  Lazy,
  Eager,
  Preload,
  Prefetch,
  Cache as CacheIcon,
  Memoize,
  Debounce,
  Throttle,
  Batch,
  Bulk,
  Streaming,
  Realtime,
  Live,
  Sync,
  Async as AsyncIcon,
  Blocking,
  NonBlocking,
  Concurrent as ConcurrentIcon,
  Parallel as ParallelIcon,
  Sequential,
  Serial,
  Batch as BatchIcon,
  Queue as QueueSymbol,
  Stack as StackIcon,
  Heap as HeapIcon,
  Tree,
  Graph,
  Node as NodeIcon,
  Edge,
  Vertex,
  Path,
  Cycle,
  Acyclic,
  Directed,
  Undirected,
  Weighted,
  Unweighted,
  Bipartite,
  Complete,
  Sparse,
  Dense,
  Connected,
  Disconnected,
  Strongly,
  Weakly,
  Topological,
  Breadth,
  Depth,
  Dijkstra,
  Floyd,
  Warshall,
  Bellman,
  Ford,
  Kruskal,
  Prim,
  Boruvka,
  Tarjan,
  Kosaraju,
  Articulation,
  Bridge as BridgeIcon,
  Cut,
  Flow,
  Capacity,
  Residual,
  Augmenting,
  Shortest,
  Longest,
  Hamiltonian,
  Eulerian,
  Planar,
  Biconnected,
  Triconnected,
  Chordal,
  Perfect,
  Interval,
  Comparability,
  Permutation,
  Cograph,
  Modular,
  Decomposition,
  Treewidth,
  Pathwidth,
  Branchwidth,
  Cliquewidth,
  Rankwidth,
  Cutwidth,
  Bandwidth,
  Bisection,
  Expansion,
  Conductance,
  Mixing,
  Spectral,
  Laplacian,
  Adjacency,
  Incidence,
  Distance,
  Eccentricity,
  Radius,
  Diameter,
  Girth,
  Circumference,
  Chromatic,
  Clique,
  Independent,
  Dominating,
  Vertex as VertexIcon,
  Cover,
  Packing,
  Matching,
  Perfect as PerfectIcon,
  Maximum,
  Minimum,
  Maximal,
  Minimal,
  Optimal,
  Suboptimal,
  Approximation,
  Heuristic,
  Greedy,
  Dynamic,
  Programming,
  Divide,
  Conquer,
  Backtracking,
  Branch as BranchIcon,
  Bound,
  Prune,
  Memoization,
  Tabulation,
  Recursion as RecursionIcon,
  Iteration as IterationIcon,
  Simulation,
  Modeling,
  Optimization,
  Constraint,
  Satisfaction,
  Linear,
  Integer,
  Quadratic,
  Convex,
  Nonconvex,
  Continuous,
  Discrete,
  Combinatorial,
  Stochastic,
  Deterministic,
  Probabilistic,
  Statistical,
  Bayesian,
  Frequentist,
  Parametric,
  Nonparametric,
  Distribution,
  Probability,
  Density,
  Cumulative,
  Quantile,
  Percentile,
  Confidence,
  Interval,
  Hypothesis,
  Test,
  Significance,
  Pvalue,
  Alpha,
  Beta,
  Power,
  Effect,
  Size,
  Sample,
  Population,
  Sampling,
  Bias,
  Variance as VarianceIcon,
  Covariance,
  Correlation as CorrelationIcon,
  Causation,
  Regression as RegressionIcon,
  Classification,
  Clustering,
  Dimensionality,
  Reduction,
  Feature,
  Selection,
  Extraction,
  Engineering,
  Preprocessing,
  Normalization,
  Standardization,
  Scaling,
  Transformation,
  Encoding,
  Decoding,
  Compression,
  Decompression,
  Encryption,
  Decryption,
  Hashing,
  Signing,
  Verification,
  Authentication,
  Authorization,
  Access,
  Control,
  Permission,
  Role,
  User as UserIcon,
  Group,
  Organization,
  Team,
  Department,
  Division,
  Company,
  Enterprise,
  Business,
  Commercial,
  Industrial,
  Academic,
  Research,
  Development,
  Innovation,
  Invention,
  Discovery,
  Creation,
  Design as DesignIcon,
  Art,
  Craft,
  Skill,
  Talent,
  Ability,
  Capability,
  Competency,
  Proficiency,
  Expertise,
  Mastery,
  Knowledge,
  Wisdom,
  Understanding,
  Comprehension,
  Insight,
  Intuition,
  Perception,
  Awareness,
  Consciousness,
  Mindfulness,
  Attention,
  Focus as FocusSymbol,
  Concentration,
  Meditation,
  Reflection,
  Contemplation,
  Introspection,
  Examination,
  Analysis,
  Synthesis,
  Evaluation,
  Judgment,
  Decision,
  Choice,
  Option,
  Alternative,
  Possibility,
  Probability as ProbabilityIcon,
  Certainty,
  Uncertainty,
  Risk,
  Reward,
  Benefit,
  Cost,
  Value,
  Price,
  Worth,
  Merit,
  Quality,
  Quantity,
  Measure as MeasureIcon,
  Unit,
  Scale,
  Ratio,
  Proportion,
  Percentage,
  Fraction,
  Decimal,
  Integer as IntegerIcon,
  Real,
  Complex,
  Imaginary,
  Rational,
  Irrational,
  Transcendental,
  Algebraic,
  Arithmetic,
  Geometric,
  Harmonic,
  Logarithmic,
  Exponential,
  Trigonometric,
  Hyperbolic,
  Inverse,
  Derivative,
  Integral,
  Differential,
  Partial,
  Total,
  Absolute,
  Relative,
  Comparative,
  Superlative,
  Positive,
  Negative,
  Neutral,
  Null as NullIcon,
  Void,
  Empty,
  Full,
  Partial as PartialIcon,
  Complete as CompleteIcon,
  Incomplete as IncompleteIcon,
  Finished,
  Unfinished,
  Started,
  Stopped,
  Paused,
  Resumed,
  Continued,
  Discontinued,
  Terminated,
  Cancelled,
  Aborted,
  Failed,
  Succeeded,
  Passed,
  Skipped,
  Ignored,
  Excluded,
  Included,
  Added,
  Removed,
  Deleted,
  Updated,
  Modified,
  Changed,
  Unchanged,
  Same,
  Different,
  Similar,
  Identical,
  Unique,
  Duplicate,
  Original,
  Copy as CopySymbol,
  Clone,
  Replica,
  Mirror,
  Reflection,
  Shadow,
  Silhouette,
  Outline,
  Sketch,
  Draft,
  Prototype,
  Model,
  Example as ExampleIcon,
  Sample as SampleIcon,
  Instance,
  Case,
  Scenario,
  Situation,
  Context,
  Environment,
  Setting,
  Configuration,
  Setup,
  Installation,
  Deployment,
  Release as ReleaseIcon,
  Version as VersionIcon,
  Update,
  Upgrade,
  Downgrade,
  Rollback,
  Patch,
  Hotfix,
  Bugfix,
  Enhancement as EnhancementIcon,
  Improvement,
  Optimization,
  Refactoring,
  Cleanup,
  Maintenance,
  Support,
  Help,
  Assistance,
  Guidance,
  Direction,
  Instruction,
  Tutorial as TutorialIcon,
  Guide as GuideIcon,
  Manual,
  Documentation as DocumentationIcon,
  Reference,
  Specification,
  Standard,
  Protocol,
  Format,
  Schema,
  Structure,
  Organization as OrganizationIcon,
  Arrangement,
  Order,
  Sequence as SequenceIcon,
  Series,
  Chain,
  Link as LinkIcon,
  Connection,
  Relation,
  Relationship,
  Association as AssociationIcon,
  Partnership,
  Collaboration,
  Cooperation,
  Teamwork,
  Synergy,
  Harmony,
  Balance,
  Equilibrium,
  Stability,
  Consistency,
  Reliability,
  Dependability,
  Trustworthiness,
  Integrity,
  Honesty,
  Transparency,
  Clarity,
  Simplicity,
  Complexity,
  Sophistication,
  Elegance,
  Beauty,
  Aesthetics,
  Style as StyleIcon,
  Fashion,
  Trend as TrendIcon,
  Pattern as PatternIcon,
  Theme as ThemeIcon,
  Mood,
  Atmosphere,
  Ambiance,
  Feeling,
  Emotion,
  Sentiment,
  Attitude,
  Perspective,
  Viewpoint,
  Opinion,
  Belief,
  Conviction,
  Faith,
  Trust,
  Confidence,
  Assurance,
  Guarantee,
  Promise,
  Commitment,
  Dedication,
  Devotion,
  Loyalty,
  Faithfulness,
  Reliability as ReliabilityIcon,
  Consistency as ConsistencyIcon,
  Stability as StabilityIcon,
  Durability,
  Longevity,
  Sustainability,
  Maintainability,
  Scalability,
  Flexibility,
  Adaptability,
  Versatility,
  Modularity,
  Extensibility,
  Customizability,
  Configurability,
  Personalization,
  Individualization,
  Specialization,
  Generalization,
  Abstraction as AbstractionIcon,
  Concrete as ConcreteIcon,
  Specific,
  General,
  Universal,
  Particular,
  Special,
  Ordinary,
  Common,
  Rare,
  Unusual,
  Exceptional,
  Outstanding,
  Excellent,
  Superior,
  Inferior,
  Average,
  Typical,
  Standard as StandardIcon,
  Normal,
  Abnormal,
  Regular,
  Irregular,
  Consistent as ConsistentIcon,
  Inconsistent,
  Stable as StableIcon,
  Unstable,
  Steady,
  Unsteady,
  Constant as ConstantIcon,
  Variable as VariableIcon,
  Fixed,
  Flexible as FlexibleIcon,
  Rigid,
  Soft,
  Hard,
  Solid,
  Liquid,
  Gas,
  Plasma,
  Matter,
  Energy,
  Force,
  Motion,
  Rest,
  Static,
  Dynamic as DynamicIcon,
  Kinetic,
  Potential,
  Mechanical,
  Thermal,
  Electrical,
  Magnetic,
  Electromagnetic,
  Nuclear,
  Chemical,
  Biological,
  Physical,
  Mental,
  Psychological,
  Emotional,
  Social,
  Cultural,
  Political,
  Economic,
  Environmental,
  Technological,
  Scientific,
  Mathematical,
  Logical,
  Philosophical,
  Ethical,
  Moral,
  Legal as LegalIcon,
  Illegal,
  Legitimate,
  Illegitimate,
  Valid,
  Invalid,
  True,
  False,
  Correct,
  Incorrect,
  Right,
  Wrong,
  Good,
  Bad,
  Better,
  Worse,
  Best,
  Worst,
  High,
  Low,
  Higher,
  Lower,
  Highest,
  Lowest,
  Top,
  Bottom,
  First as FirstIcon,
  Last,
  Middle,
  Center,
  Left,
  Right,
  Up,
  Down,
  Forward,
  Backward,
  Front,
  Back,
  Inside,
  Outside,
  Inner,
  Outer,
  Internal,
  External,
  Public,
  Private,
  Open,
  Closed,
  Visible,
  Hidden,
  Shown,
  Concealed,
  Revealed,
  Exposed,
  Protected,
  Secure,
  Insecure,
  Safe,
  Unsafe,
  Dangerous,
  Risky,
  Cautious,
  Careful,
  Careless,
  Reckless,
  Prudent,
  Imprudent,
  Wise,
  Foolish,
  Smart,
  Stupid,
  Intelligent,
  Unintelligent,
  Clever,
  Dull,
  Bright,
  Dark,
  Light,
  Heavy,
  Thin,
  Thick,
  Narrow,
  Wide,
  Short,
  Long,
  Tall,
  Small,
  Large,
  Big,
  Tiny,
  Huge,
  Gigantic,
  Massive,
  Enormous,
  Immense,
  Vast,
  Infinite,
  Finite,
  Limited,
  Unlimited,
  Boundless,
  Endless,
  Eternal,
  Temporary,
  Permanent,
  Transient,
  Persistent,
  Continuous as ContinuousIcon,
  Discontinuous,
  Smooth,
  Rough,
  Sharp,
  Blunt,
  Pointed,
  Round,
  Square as SquareIcon,
  Circular,
  Triangular,
  Rectangular,
  Oval,
  Curved,
  Straight,
  Bent,
  Twisted,
  Spiral,
  Helical,
  Coiled,
  Wrapped,
  Folded,
  Unfolded,
  Expanded,
  Collapsed,
  Compressed,
  Stretched,
  Contracted,
  Extended,
  Retracted,
  Projected,
  Introverted,
  Extroverted,
  Outgoing,
  Shy,
  Bold,
  Timid,
  Brave,
  Cowardly,
  Courageous,
  Fearful,
  Confident as ConfidentIcon,
  Insecure as InsecureIcon,
  Secure as SecureIcon,
  Assured,
  Uncertain as UncertainIcon,
  Sure,
  Unsure,
  Positive as PositiveIcon,
  Negative as NegativeIcon,
  Optimistic,
  Pessimistic,
  Hopeful,
  Hopeless,
  Cheerful,
  Gloomy,
  Happy,
  Sad,
  Joyful,
  Sorrowful,
  Excited,
  Bored,
  Interested,
  Disinterested,
  Engaged,
  Disengaged,
  Active,
  Inactive,
  Passive,
  Reactive,
  Proactive,
  Responsive,
  Unresponsive,
  Sensitive,
  Insensitive,
  Aware,
  Unaware,
  Conscious as ConsciousIcon,
  Unconscious,
  Awake,
  Asleep,
  Alert,
  Drowsy,
  Energetic,
  Tired,
  Fresh,
  Stale,
  New,
  Old,
  Young,
  Ancient,
  Modern as ModernIcon,
  Contemporary,
  Traditional,
  Conventional,
  Unconventional,
  Classic as ClassicIcon,
  Vintage as VintageIcon,
  Retro as RetroIcon,
  Futuristic,
  Advanced,
  Primitive,
  Sophisticated as SophisticatedIcon,
  Simple,
  Complex as ComplexIcon,
  Complicated,
  Easy,
  Difficult,
  Hard as HardIcon,
  Soft as SoftIcon,
  Gentle,
  Harsh,
  Mild,
  Severe,
  Intense,
  Weak,
  Strong,
  Powerful,
  Powerless,
  Influential,
  Insignificant,
  Important,
  Unimportant,
  Significant,
  Insignificant as InsignificantIcon,
  Meaningful,
  Meaningless,
  Purposeful,
  Purposeless,
  Useful,
  Useless,
  Valuable,
  Worthless,
  Precious,
  Cheap as CheapIcon,
  Expensive as ExpensiveIcon,
  Affordable as AffordableIcon,
  Costly,
  Priceless,
  Free as FreeIcon,
  Paid as PaidIcon,
  Subscription as SubscriptionIcon,
  Premium as PremiumIcon,
  Basic,
  Standard as StandardSymbol,
  Advanced as AdvancedIcon,
  Professional as ProfessionalIcon,
  Enterprise as EnterpriseIcon,
  Personal,
  Business as BusinessIcon,
  Commercial as CommercialIcon,
  Industrial as IndustrialIcon,
  Residential,
  Educational,
  Medical,
  Legal as LegalSymbol,
  Financial,
  Technical,
  Creative as CreativeIcon,
  Artistic as ArtisticIcon,
  Scientific as ScientificIcon,
  Research as ResearchIcon,
  Development as DevelopmentIcon,
  Innovation as InnovationIcon,
  Invention as InventionIcon,
  Discovery as DiscoveryIcon,
  Creation as CreationIcon,
  Production,
  Manufacturing,
  Construction,
  Architecture,
  Engineering,
  Design as DesignSymbol,
  Planning,
  Strategy,
  Management,
  Leadership,
  Administration,
  Operations,
  Sales,
  Marketing,
  Advertising,
  Promotion,
  Publicity,
  Communication,
  Networking,
  Collaboration as CollaborationIcon,
  Partnership as PartnershipIcon,
  Alliance,
  Union,
  Association as AssociationSymbol,
  Organization as OrganizationSymbol,
  Institution,
  Corporation,
  Company as CompanyIcon,
  Firm,
  Agency,
  Bureau,
  Department as DepartmentIcon,
  Division as DivisionIcon,
  Branch as BranchSymbol,
  Office,
  Studio,
  Workshop,
  Laboratory,
  Facility,
  Center,
  Hub,
  Base,
  Headquarters,
  Campus,
  Site,
  Location as LocationSymbol,
  Address,
  Destination,
  Direction as DirectionIcon,
  Route as RouteIcon,
  Path as PathIcon,
  Way,
  Road,
  Street,
  Avenue,
  Lane,
  Drive,
  Boulevard,
  Highway,
  Freeway,
  Bridge as BridgeSymbol,
  Tunnel,
  Intersection,
  Junction,
  Crossroads,
  Roundabout,
  Traffic,
  Vehicle,
  Car as CarIcon,
  Truck as TruckSymbol,
  Bus as BusIcon,
  Train as TrainIcon,
  Subway,
  Tram,
  Trolley,
  Bicycle,
  Motorcycle,
  Scooter,
  Skateboard,
  Rollerblade,
  Wheelchair,
  Stroller,
  Walker,
  Cane,
  Crutch,
  Prosthetic,
  Implant,
  Device,
  Gadget,
  Tool,
  Instrument,
  Equipment,
  Machine,
  Appliance,
  Apparatus,
  System,
  Network,
  Infrastructure,
  Platform,
  Framework,
  Library,
  Package,
  Module,
  Component as ComponentIcon,
  Element as ElementIcon,
  Part,
  Piece,
  Fragment as FragmentIcon,
  Section,
  Segment,
  Division as DivisionSymbol,
  Category,
  Class as ClassIcon,
  Type,
  Kind,
  Sort,
  Variety,
  Species,
  Genus,
  Family,
  Order as OrderIcon,
  Hierarchy,
  Structure as StructureIcon,
  Architecture as ArchitectureIcon,
  Design as DesignAlternate,
  Pattern as PatternSymbol,
  Template as TemplateIcon,
  Model as ModelIcon,
  Schema as SchemaIcon,
  Format as FormatIcon,
  Standard as StandardAlternate,
  Specification as SpecificationIcon,
  Protocol as ProtocolIcon,
  Interface as InterfaceIcon,
  Api,
  Sdk,
  Framework as FrameworkIcon,
  Library as LibraryIcon,
  Package as PackageSymbol,
  Module as ModuleIcon,
  Component as ComponentSymbol,
  Service,
  Application,
  Program,
  Software,
  Hardware,
  Firmware,
  Middleware,
  Driver,
  Plugin,
  Extension,
  Addon,
  Widget as WidgetIcon,
  Control,
  Input,
  Output,
  Display,
  Screen,
  Monitor as MonitorSymbol,
  Display as DisplayIcon,
  Projection,
  Presentation,
  Slideshow,
  Demo as DemoIcon,
  Showcase,
  Exhibition,
  Gallery,
  Portfolio,
  Collection,
  Archive as ArchiveSymbol,
  Storage,
  Repository,
  Database as DatabaseSymbol,
  Datastore,
  Warehouse,
  Mart,
  Lake,
  Pool,
  Stream as StreamIcon,
  River,
  Ocean,
  Sea,
  Lake as LakeIcon,
  Pond,
  Pool as PoolIcon,
  Well,
  Spring,
  Source,
  Origin,
  Root,
  Base as BaseIcon,
  Foundation,
  Ground,
  Floor,
  Ceiling,
  Roof,
  Wall,
  Door,
  Window,
  Gate,
  Fence,
  Barrier,
  Boundary,
  Border,
  Edge,
  Corner,
  Side,
  Face,
  Surface,
  Texture as TextureIcon,
  Material,
  Substance,
  Matter as MatterIcon,
  Element as ElementSymbol,
  Compound,
  Mixture,
  Solution,
  Suspension,
  Emulsion,
  Colloid,
  Gel,
  Foam,
  Aerosol,
  Plasma as PlasmaIcon,
  Gas as GasIcon,
  Liquid as LiquidIcon,
  Solid as SolidIcon,
  Crystal,
  Amorphous,
  Crystalline,
  Metallic,
  Nonmetallic,
  Organic as OrganicIcon,
  Inorganic,
  Synthetic,
  Natural as NaturalIcon,
  Artificial,
  Synthetic as SyntheticIcon,
  Manufactured,
  Handmade,
  Crafted,
  Designed,
  Engineered,
  Built,
  Constructed,
  Assembled,
  Fabricated,
  Produced,
  Created,
  Made,
  Generated,
  Developed,
  Formed,
  Shaped,
  Molded,
  Carved,
  Sculpted,
  Painted,
  Drawn,
  Sketched,
  Illustrated,
  Photographed,
  Filmed,
  Recorded,
  Captured,
  Documented,
  Archived,
  Stored,
  Saved,
  Preserved,
  Maintained,
  Kept,
  Held,
  Retained,
  Sustained,
  Supported,
  Backed,
  Sponsored,
  Funded,
  Financed,
  Invested,
  Bought,
  Sold,
  Traded,
  Exchanged,
  Bartered,
  Negotiated,
  Agreed,
  Contracted,
  Committed,
  Promised,
  Guaranteed,
  Assured,
  Insured,
  Protected,
  Secured,
  Safeguarded,
  Defended,
  Guarded,
  Watched,
  Monitored,
  Observed,
  Supervised,
  Controlled,
  Managed,
  Administered,
  Governed,
  Regulated,
  Ruled,
  Led,
  Directed,
  Guided,
  Instructed,
  Taught,
  Educated,
  Trained,
  Coached,
  Mentored,
  Advised,
  Counseled,
  Consulted,
  Assisted,
  Helped,
  Supported as SupportedIcon,
  Aided,
  Served,
  Provided,
  Supplied,
  Delivered,
  Distributed,
  Shared,
  Communicated,
  Transmitted,
  Sent,
  Received,
  Accepted,
  Approved,
  Confirmed,
  Verified,
  Validated,
  Authenticated,
  Authorized,
  Permitted,
  Allowed,
  Enabled,
  Activated,
  Turned,
  Switched,
  Toggled,
  Changed,
  Modified,
  Altered,
  Adjusted,
  Adapted,
  Customized,
  Configured,
  Set,
  Established,
  Founded,
  Started,
  Initiated,
  Launched,
  Opened,
  Began,
  Commenced,
  Originated,
  Created as CreatedIcon,
  Invented,
  Discovered,
  Found,
  Located,
  Identified,
  Recognized,
  Acknowledged,
  Admitted,
  Confessed,
  Revealed,
  Disclosed,
  Exposed,
  Shown,
  Displayed,
  Presented,
  Demonstrated,
  Exhibited,
  Performed,
  Executed,
  Implemented,
  Applied,
  Used,
  Utilized,
  Employed,
  Engaged,
  Involved,
  Participated,
  Contributed,
  Shared as SharedIcon,
  Collaborated,
  Cooperated,
  Worked,
  Operated,
  Functioned,
  Performed as PerformedIcon,
  Acted,
  Behaved,
  Conducted,
  Managed as ManagedIcon,
  Handled,
  Dealt,
  Processed,
  Treated,
  Addressed,
  Resolved,
  Solved,
  Fixed,
  Repaired,
  Restored,
  Recovered,
  Healed,
  Cured,
  Treated as TreatedIcon,
  Helped as HelpedIcon,
  Assisted as AssistedIcon,
  Supported as SupportIcon,
  Backed as BackedIcon,
  Endorsed,
  Recommended,
  Suggested,
  Proposed,
  Offered,
  Provided as ProvidedIcon,
  Supplied as SuppliedIcon,
  Delivered as DeliveredIcon,
  Shipped,
  Sent as SentIcon,
  Mailed,
  Posted,
  Published,
  Released,
  Issued,
  Distributed as DistributedIcon,
  Spread,
  Shared as SharedSymbol,
  Broadcasted,
  Transmitted as TransmittedIcon,
  Communicated as CommunicatedIcon,
  Conveyed,
  Expressed,
  Articulated,
  Stated,
  Declared,
  Announced,
  Proclaimed,
  Advertised,
  Promoted,
  Marketed,
  Sold as SoldIcon,
  Offered as OfferedIcon,
  Proposed as ProposedIcon,
  Suggested as SuggestedIcon,
  Recommended as RecommendedIcon,
  Advised as AdvisedIcon,
  Counseled as CounseledIcon,
  Guided as GuidedIcon,
  Directed as DirectedIcon,
  Led as LedIcon,
  Managed as ManagedSymbol,
  Supervised as SupervisedIcon,
  Controlled as ControlledIcon,
  Regulated as RegulatedIcon,
  Governed as GovernedIcon,
  Administered as AdministeredIcon,
  Organized as OrganizedIcon,
  Arranged as ArrangedIcon,
  Planned as PlannedIcon,
  Scheduled,
  Timed,
  Coordinated,
  Synchronized,
  Aligned,
  Matched,
  Paired,
  Coupled,
  Connected as ConnectedIcon,
  Linked as LinkedIcon,
  Joined,
  United,
  Combined,
  Merged,
  Integrated,
  Incorporated,
  Included as IncludedIcon,
  Added as AddedIcon,
  Inserted,
  Embedded,
  Attached,
  Appended,
  Extended as ExtendedIcon,
  Expanded as ExpandedIcon,
  Enlarged,
  Increased,
  Grown,
  Developed as DevelopedIcon,
  Evolved,
  Progressed,
  Advanced as AdvancedSymbol,
  Improved as ImprovedIcon,
  Enhanced as EnhancedSymbol,
  Optimized as OptimizedIcon,
  Refined,
  Polished,
  Perfected,
  Completed as CompletedIcon,
  Finished as FinishedIcon,
  Done,
  Accomplished,
  Achieved,
  Attained,
  Reached,
  Obtained,
  Gained,
  Earned,
  Won,
  Succeeded as SucceededIcon,
  Triumphed,
  Conquered,
  Overcome,
  Defeated,
  Beat,
  Surpassed,
  Exceeded,
  Outperformed,
  Outdone,
  Outshined,
  Excelled,
  Mastered,
  Dominated,
  Controlled as ControlledSymbol,
  Commanded,
  Ordered,
  Instructed as InstructedIcon,
  Directed as DirectedSymbol,
  Guided as GuidedSymbol,
  Led as LedSymbol,
  Influenced,
  Persuaded,
  Convinced,
  Motivated,
  Inspired,
  Encouraged,
  Supported as SupportedSymbol,
  Helped as HelpedSymbol,
  Assisted as AssistedSymbol,
  Aided as AidedIcon,
  Served as ServedIcon,
  Provided as ProvidedSymbol,
  Supplied as SuppliedSymbol,
  Offered as OfferedSymbol,
  Given,
  Delivered as DeliveredSymbol,
  Distributed as DistributedSymbol,
  Shared as SharedAlternate,
  Communicated as CommunicatedSymbol,
  Transmitted as TransmittedSymbol,
  Sent as SentSymbol,
  Received as ReceivedIcon,
  Accepted as AcceptedIcon,
  Approved as ApprovedIcon,
  Confirmed as ConfirmedIcon,
  Verified as VerifiedIcon,
  Validated as ValidatedIcon,
  Authenticated as AuthenticatedIcon,
  Authorized as AuthorizedIcon,
  Permitted as PermittedIcon,
  Allowed as AllowedIcon,
  Enabled as EnabledIcon,
  Activated as ActivatedIcon,
  Started as StartedIcon,
  Initiated as InitiatedIcon,
  Launched as LaunchedIcon,
  Opened as OpenedIcon,
  Began as BeganIcon,
  Commenced as CommencedIcon,
  Originated as OriginatedIcon,
  Created as CreatedSymbol,
  Made as MadeIcon,
  Built as BuiltIcon,
  Constructed as ConstructedIcon,
  Assembled as AssembledIcon,
  Manufactured as ManufacturedIcon,
  Produced as ProducedIcon,
  Generated as GeneratedIcon,
  Developed as DevelopedSymbol,
  Designed as DesignedIcon,
  Engineered as EngineeredIcon,
  Crafted as CraftedIcon,
  Formed as FormedIcon,
  Shaped as ShapedIcon,
  Molded as MoldedIcon,
  Carved as CarvedIcon,
  Sculpted as SculptedIcon,
  Painted as PaintedIcon,
  Drawn as DrawnIcon,
  Sketched as SketchedIcon,
  Illustrated as IllustratedIcon,
  Photographed as PhotographedIcon,
  Filmed as FilmedIcon,
  Recorded as RecordedIcon,
  Captured as CapturedIcon,
  Documented as DocumentedIcon,
  Archived as ArchivedIcon,
  Stored as StoredIcon,
  Saved as SavedIcon,
  Preserved as PreservedIcon,
  Maintained as MaintainedIcon,
  Kept as KeptIcon,
  Held as HeldIcon,
  Retained as RetainedIcon,
  Sustained as SustainedIcon,
  Supported as SupportedAlternate,
  Backed as BackedSymbol,
  Sponsored as SponsoredIcon,
  Funded as FundedIcon,
  Financed as FinancedIcon,
  Invested as InvestedIcon,
  Bought as BoughtIcon,
  Purchased,
  Acquired,
  Obtained as ObtainedIcon,
  Gained as GainedIcon,
  Earned as EarnedIcon,
  Won as WonIcon,
  Received as ReceivedSymbol,
  Got,
  Took,
  Collected,
  Gathered,
  Assembled as AssembledSymbol,
  Organized as OrganizedSymbol,
  Arranged as ArrangedSymbol,
  Sorted,
  Classified,
  Categorized,
  Grouped,
  Divided,
  Separated,
  Split,
  Broken,
  Fractured,
  Cracked,
  Damaged,
  Harmed,
  Injured,
  Hurt,
  Wounded,
  Bruised,
  Scratched,
  Scraped,
  Cut,
  Sliced,
  Pierced,
  Punctured,
  Perforated,
  Holed,
  Torn,
  Ripped,
  Shredded,
  Destroyed,
  Demolished,
  Ruined,
  Wrecked,
  Smashed,
  Crushed,
  Compressed as CompressedIcon,
  Squeezed,
  Pressed,
  Pushed,
  Pulled,
  Dragged,
  Lifted,
  Raised,
  Lowered,
  Dropped,
  Fell,
  Fallen,
  Collapsed as CollapsedIcon,
  Tumbled,
  Rolled,
  Slid,
  Glided,
  Floated,
  Drifted,
  Sailed,
  Flowed,
  Streamed,
  Poured,
  Spilled,
  Leaked,
  Dripped,
  Oozed,
  Seeped,
  Soaked,
  Absorbed,
  Sucked,
  Inhaled,
  Exhaled,
  Breathed,
  Gasped,
  Sighed,
  Yawned,
  Sneezed,
  Coughed,
  Choked,
  Gagged,
  Swallowed,
  Ate,
  Consumed,
  Devoured,
  Digested,
  Metabolized,
  Burned,
  Combusted,
  Ignited,
  Lit,
  Illuminated,
  Brightened,
  Darkened,
  Dimmed,
  Faded,
  Disappeared,
  Vanished,
  Evaporated,
  Dissolved,
  Melted,
  Frozen,
  Solidified,
  Crystallized,
  Hardened,
  Softened,
  Warmed,
  Cooled,
  Heated,
  Chilled,
  Frozen as FrozenIcon,
  Thawed,
  Defrosted,
  Dried,
  Moistened,
  Wetted,
  Soaked as SoakedIcon,
  Drenched,
  Saturated,
  Flooded,
  Overflowed,
  Filled,
  Emptied,
  Drained,
  Exhausted,
  Depleted,
  Consumed as ConsumedIcon,
  Used as UsedIcon,
  Utilized as UtilizedIcon,
  Employed as EmployedIcon,
  Applied as AppliedIcon,
  Implemented as ImplementedIcon,
  Executed as ExecutedIcon,
  Performed as PerformedSymbol,
  Acted as ActedIcon,
  Behaved as BehavedIcon,
  Conducted as ConductedIcon,
  Operated as OperatedIcon,
  Functioned as FunctionedIcon,
  Worked as WorkedIcon,
  Ran,
  Moved,
  Traveled,
  Journeyed,
  Migrated,
  Relocated,
  Transferred,
  Transported,
  Carried,
  Conveyed as ConveyedIcon,
  Delivered as DeliveredAlternate,
  Shipped as ShippedIcon,
  Sent as SentAlternate,
  Transmitted as TransmittedAlternate,
  Broadcast,
  Communicated as CommunicatedAlternate,
  Shared as SharedFinal,
  Distributed as DistributedFinal,
  Spread as SpreadIcon,
  Scattered,
  Dispersed,
  Diffused,
  Radiated,
  Emitted,
  Released as ReleasedIcon,
  Discharged,
  Expelled,
  Ejected,
  Thrown,
  Hurled,
  Launched as LaunchedSymbol,
  Fired,
  Shot,
  Aimed,
  Targeted,
  Focused as FocusedIcon,
  Concentrated as ConcentratedIcon,
  Centered,
  Balanced as BalancedIcon,
  Stabilized,
  Equilibrated,
  Harmonized,
  Synchronized as SynchronizedIcon,
  Coordinated as CoordinatedIcon,
  Aligned as AlignedIcon,
  Matched as MatchedIcon,
  Paired as PairedIcon,
  Coupled as CoupledIcon,
  Connected as ConnectedSymbol,
  Linked as LinkedSymbol,
  Joined as JoinedIcon,
  United as UnitedIcon,
  Combined as CombinedIcon,
  Merged as MergedIcon,
  Integrated as IntegratedIcon,
  Incorporated as IncorporatedIcon,
  Included as IncludedSymbol,
  Added as AddedSymbol,
  Inserted as InsertedIcon,
  Embedded as EmbeddedIcon,
  Attached as AttachedIcon,
  Appended as AppendedIcon,
  Extended as ExtendedSymbol,
  Expanded as ExpandedSymbol,
  Enlarged as EnlargedIcon,
  Increased as IncreasedIcon,
  Grown as GrownIcon,
  Developed as DevelopedFinal,
  Evolved as EvolvedIcon,
  Progressed as ProgressedIcon,
  Advanced as AdvancedFinal,
  Improved as ImprovedSymbol,
  Enhanced as EnhancedFinal,
  Optimized as OptimizedSymbol,
  Refined as RefinedIcon,
  Polished as PolishedIcon,
  Perfected as PerfectedIcon,
  Completed as CompletedSymbol,
  Finished as FinishedSymbol,
  Done as DoneIcon,
  Accomplished as AccomplishedIcon,
  Achieved as AchievedIcon,
  Attained as AttainedIcon,
  Reached as ReachedIcon,
  Obtained as ObtainedSymbol,
  Gained as GainedSymbol,
  Earned as EarnedSymbol,
  Won as WonSymbol,
  Succeeded as SucceededSymbol
} from 'lucide-react';
import { ComponentPaletteItem } from './types';

export const DEFAULT_COLORS = [
  '#3b82f6', '#ef4444', '#10b981', '#f59e0b', 
  '#8b5cf6', '#ec4899', '#6b7280', '#000000',
  '#ffffff', '#f3f4f6', '#ddd6fe', '#fef3c7',
  '#dcfce7', '#fee2e2', '#dbeafe', '#f3e8ff'
];

export const COMPONENT_PALETTE_ITEMS: ComponentPaletteItem[] = [
  // Basic Input Fields
  {
    type: 'text',
    label: 'Text Input',
    icon: Type,
    category: 'input',
    defaultProperties: {
      label: 'Text Input',
      placeholder: 'Enter text...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'textarea',
    label: 'Textarea',
    icon: FileText,
    category: 'input',
    defaultProperties: {
      label: 'Textarea',
      placeholder: 'Enter long text...',
      required: false,
      size: { width: 300, height: 80 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'email',
    label: 'Email',
    icon: Mail,
    category: 'input',
    defaultProperties: {
      label: 'Email',
      placeholder: 'Enter email...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'number',
    label: 'Number',
    icon: Hash,
    category: 'input',
    defaultProperties: {
      label: 'Number',
      placeholder: 'Enter number...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'password',
    label: 'Password',
    icon: Lock,
    category: 'input',
    defaultProperties: {
      label: 'Password',
      placeholder: 'Enter password...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'tel',
    label: 'Phone',
    icon: Phone,
    category: 'input',
    defaultProperties: {
      label: 'Phone Number',
      placeholder: 'Enter phone number...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'url',
    label: 'URL',
    icon: Globe,
    category: 'input',
    defaultProperties: {
      label: 'Website URL',
      placeholder: 'https://example.com',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  
  // Date & Time Inputs
  {
    type: 'date',
    label: 'Date',
    icon: Calendar,
    category: 'input',
    defaultProperties: {
      label: 'Date',
      placeholder: 'Select date...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'time',
    label: 'Time',
    icon: Clock,
    category: 'input',
    defaultProperties: {
      label: 'Time',
      placeholder: 'Select time...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'datetime',
    label: 'Date & Time',
    icon: CalendarIcon,
    category: 'input',
    defaultProperties: {
      label: 'Date & Time',
      placeholder: 'Select date and time...',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },

  // Selection Components
  {
    type: 'select',
    label: 'Select',
    icon: ChevronDown,
    category: 'selection',
    defaultProperties: {
      label: 'Select',
      placeholder: 'Choose option...',
      required: false,
      options: ['Option 1', 'Option 2', 'Option 3'],
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'multiselect',
    label: 'Multi Select',
    icon: CheckSquare,
    category: 'selection',
    defaultProperties: {
      label: 'Multi Select',
      placeholder: 'Choose multiple options...',
      required: false,
      options: ['Option 1', 'Option 2', 'Option 3'],
      size: { width: 300, height: 120 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'radio',
    label: 'Radio',
    icon: Circle,
    category: 'selection',
    defaultProperties: {
      label: 'Radio Group',
      required: false,
      options: ['Option 1', 'Option 2', 'Option 3'],
      size: { width: 300, height: 120 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    icon: CheckSquare,
    category: 'selection',
    defaultProperties: {
      label: 'Checkbox Group',
      required: false,
      options: ['Option 1', 'Option 2', 'Option 3'],
      size: { width: 300, height: 120 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'toggle',
    label: 'Toggle Switch',
    icon: ToggleLeft,
    category: 'selection',
    defaultProperties: {
      label: 'Toggle Switch',
      required: false,
      size: { width: 300, height: 50 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },

  // Advanced Input Components
  {
    type: 'color',
    label: 'Color Picker',
    icon: Palette,
    category: 'advanced',
    defaultProperties: {
      label: 'Color Picker',
      required: false,
      size: { width: 300, height: 40 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'range',
    label: 'Range Slider',
    icon: Sliders,
    category: 'advanced',
    defaultProperties: {
      label: 'Range Slider',
      required: false,
      properties: {
        min: 0,
        max: 100,
        step: 1,
        value: 50,
      },
      size: { width: 300, height: 60 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'rating',
    label: 'Star Rating',
    icon: Star,
    category: 'interactive',
    defaultProperties: {
      label: 'Star Rating',
      required: false,
      properties: {
        max: 5,
        allowHalf: true,
        showLabels: true,
      },
      size: { width: 300, height: 60 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'signature',
    label: 'Signature Pad',
    icon: PenTool,
    category: 'advanced',
    defaultProperties: {
      label: 'Signature',
      required: false,
      size: { width: 400, height: 200 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 2,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'location',
    label: 'Location Picker',
    icon: MapPin,
    category: 'advanced',
    defaultProperties: {
      label: 'Location',
      required: false,
      size: { width: 400, height: 300 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },

  // File Upload Components
  {
    type: 'file',
    label: 'File Upload',
    icon: Upload,
    category: 'advanced',
    defaultProperties: {
      label: 'File Upload',
      required: false,
      size: { width: 300, height: 100 },
      properties: {
        allowMultiple: false,
        maxSize: 10485760, // 10MB
        allowedTypes: ['.pdf', '.doc', '.docx', '.jpg', '.png'],
      },
      style: {
        backgroundColor: '#f9fafb',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 2,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'image',
    label: 'Image Upload',
    icon: Image,
    category: 'media',
    defaultProperties: {
      label: 'Image Upload',
      required: false,
      size: { width: 300, height: 200 },
      properties: {
        allowMultiple: false,
        maxSize: 5242880, // 5MB
        allowedTypes: ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
      },
      style: {
        backgroundColor: '#f9fafb',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 2,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'video',
    label: 'Video Upload',
    icon: Video,
    category: 'media',
    defaultProperties: {
      label: 'Video Upload',
      required: false,
      size: { width: 400, height: 250 },
      properties: {
        allowMultiple: false,
        maxSize: 52428800, // 50MB
        allowedTypes: ['.mp4', '.mov', '.avi', '.mkv'],
      },
      style: {
        backgroundColor: '#f9fafb',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 2,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'audio',
    label: 'Audio Upload',
    icon: Volume2,
    category: 'media',
    defaultProperties: {
      label: 'Audio Upload',
      required: false,
      size: { width: 300, height: 80 },
      properties: {
        allowMultiple: false,
        maxSize: 10485760, // 10MB
        allowedTypes: ['.mp3', '.wav', '.ogg', '.m4a'],
      },
      style: {
        backgroundColor: '#f9fafb',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 2,
        borderRadius: 8,
      }
    },
  },

  // Business Components
  {
    type: 'payment',
    label: 'Payment',
    icon: CreditCard,
    category: 'business',
    defaultProperties: {
      label: 'Payment Information',
      required: false,
      size: { width: 400, height: 300 },
      properties: {
        acceptedCards: ['visa', 'mastercard', 'amex'],
        currency: 'USD',
        amount: 0,
      },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },

  // Display Components
  {
    type: 'heading',
    label: 'Heading',
    icon: Heading1,
    category: 'display',
    defaultProperties: {
      label: 'Heading Text',
      required: false,
      properties: {
        level: 1,
        text: 'Heading Text',
      },
      size: { width: 400, height: 50 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#111827',
        borderColor: 'transparent',
        borderWidth: 0,
        borderRadius: 0,
      }
    },
  },
  {
    type: 'paragraph',
    label: 'Paragraph',
    icon: AlignLeft,
    category: 'display',
    defaultProperties: {
      label: 'Paragraph Text',
      required: false,
      properties: {
        text: 'This is a paragraph of text.',
      },
      size: { width: 400, height: 80 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: 'transparent',
        borderWidth: 0,
        borderRadius: 0,
      }
    },
  },
  {
    type: 'divider',
    label: 'Divider',
    icon: Minus,
    category: 'layout',
    defaultProperties: {
      label: 'Divider',
      required: false,
      size: { width: 400, height: 20 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 0,
      }
    },
  },
  {
    type: 'spacer',
    label: 'Spacer',
    icon: Move,
    category: 'layout',
    defaultProperties: {
      label: 'Spacer',
      required: false,
      size: { width: 400, height: 40 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#374151',
        borderColor: 'transparent',
        borderWidth: 0,
        borderRadius: 0,
      }
    },
  },

  // Interactive Components
  {
    type: 'table',
    label: 'Table',
    icon: Table,
    category: 'interactive',
    defaultProperties: {
      label: 'Table',
      required: false,
      properties: {
        rows: 3,
        columns: 3,
        headers: ['Column 1', 'Column 2', 'Column 3'],
        editable: true,
      },
      size: { width: 500, height: 200 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'matrix',
    label: 'Matrix',
    icon: Grid,
    category: 'interactive',
    defaultProperties: {
      label: 'Matrix Question',
      required: false,
      properties: {
        rows: ['Row 1', 'Row 2', 'Row 3'],
        columns: ['Column 1', 'Column 2', 'Column 3'],
        type: 'radio', // radio, checkbox, dropdown
      },
      size: { width: 500, height: 250 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'ranking',
    label: 'Ranking',
    icon: List,
    category: 'interactive',
    defaultProperties: {
      label: 'Ranking Question',
      required: false,
      properties: {
        options: ['Option 1', 'Option 2', 'Option 3'],
        instruction: 'Drag to rank from most to least important',
      },
      size: { width: 400, height: 200 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'likert',
    label: 'Likert Scale',
    icon: BarChart3,
    category: 'interactive',
    defaultProperties: {
      label: 'Likert Scale',
      required: false,
      properties: {
        statements: ['Statement 1', 'Statement 2', 'Statement 3'],
        scale: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
      },
      size: { width: 600, height: 200 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'nps',
    label: 'NPS Score',
    icon: Target,
    category: 'interactive',
    defaultProperties: {
      label: 'Net Promoter Score',
      required: false,
      properties: {
        question: 'How likely are you to recommend us to a friend?',
        leftLabel: 'Not likely',
        rightLabel: 'Very likely',
      },
      size: { width: 500, height: 100 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },

  // Layout Components
  {
    type: 'section',
    label: 'Section',
    icon: Box,
    category: 'layout',
    defaultProperties: {
      label: 'Section',
      required: false,
      properties: {
        title: 'Section Title',
        collapsible: false,
        collapsed: false,
      },
      size: { width: 600, height: 400 },
      style: {
        backgroundColor: '#f9fafb',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'tabs',
    label: 'Tabs',
    icon: Folder,
    category: 'layout',
    defaultProperties: {
      label: 'Tabs',
      required: false,
      properties: {
        tabs: [
          { id: 'tab1', label: 'Tab 1', content: 'Tab 1 Content' },
          { id: 'tab2', label: 'Tab 2', content: 'Tab 2 Content' },
        ],
      },
      size: { width: 600, height: 300 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'accordion',
    label: 'Accordion',
    icon: ChevronDown,
    category: 'layout',
    defaultProperties: {
      label: 'Accordion',
      required: false,
      properties: {
        panels: [
          { id: 'panel1', title: 'Panel 1', content: 'Panel 1 Content' },
          { id: 'panel2', title: 'Panel 2', content: 'Panel 2 Content' },
        ],
      },
      size: { width: 600, height: 200 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'card',
    label: 'Card',
    icon: Layers,
    category: 'layout',
    defaultProperties: {
      label: 'Card',
      required: false,
      properties: {
        title: 'Card Title',
        content: 'Card content goes here',
        showHeader: true,
        showFooter: false,
      },
      size: { width: 400, height: 200 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'progress',
    label: 'Progress Bar',
    icon: BarChart3,
    category: 'display',
    defaultProperties: {
      label: 'Progress Bar',
      required: false,
      properties: {
        value: 50,
        max: 100,
        showLabel: true,
        showPercentage: true,
      },
      size: { width: 400, height: 30 },
      style: {
        backgroundColor: '#f3f4f6',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },

  // Advanced Components
  {
    type: 'code',
    label: 'Code Block',
    icon: Code,
    category: 'advanced',
    defaultProperties: {
      label: 'Code Block',
      required: false,
      properties: {
        language: 'javascript',
        code: '// Enter your code here',
        editable: true,
        showLineNumbers: true,
      },
      size: { width: 500, height: 200 },
      style: {
        backgroundColor: '#1f2937',
        textColor: '#f9fafb',
        borderColor: '#374151',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'html',
    label: 'HTML Block',
    icon: Code,
    category: 'advanced',
    defaultProperties: {
      label: 'HTML Block',
      required: false,
      properties: {
        html: '<p>Enter your HTML here</p>',
        allowScripts: false,
      },
      size: { width: 500, height: 200 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'calculation',
    label: 'Calculation',
    icon: Calculator,
    category: 'advanced',
    defaultProperties: {
      label: 'Calculation',
      required: false,
      properties: {
        formula: 'field1 + field2',
        dependentFields: [],
        displayFormat: 'number',
      },
      size: { width: 300, height: 60 },
      style: {
        backgroundColor: '#f3f4f6',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 4,
      }
    },
  },
  {
    type: 'embed',
    label: 'Embed',
    icon: ExternalLink,
    category: 'advanced',
    defaultProperties: {
      label: 'Embed',
      required: false,
      properties: {
        url: 'https://example.com',
        type: 'iframe', // iframe, video, map
        allowFullscreen: true,
      },
      size: { width: 500, height: 300 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'qr',
    label: 'QR Code',
    icon: QrCode,
    category: 'display',
    defaultProperties: {
      label: 'QR Code',
      required: false,
      properties: {
        value: 'https://example.com',
        size: 128,
        errorCorrectionLevel: 'M',
      },
      size: { width: 150, height: 150 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#000000',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },
  {
    type: 'chart',
    label: 'Chart',
    icon: PieChart,
    category: 'display',
    defaultProperties: {
      label: 'Chart',
      required: false,
      properties: {
        type: 'bar', // bar, line, pie, doughnut
        data: {
          labels: ['Label 1', 'Label 2', 'Label 3'],
          datasets: [
            {
              label: 'Dataset 1',
              data: [10, 20, 30],
            },
          ],
        },
      },
      size: { width: 500, height: 300 },
      style: {
        backgroundColor: '#ffffff',
        textColor: '#374151',
        borderColor: '#d1d5db',
        borderWidth: 1,
        borderRadius: 8,
      }
    },
  },

  // Action Components
  {
    type: 'button',
    label: 'Button',
    icon: MousePointer,
    category: 'action',
    defaultProperties: {
      label: 'Button',
      required: false,
      properties: {
        text: 'Click Me',
        variant: 'primary',
        size: 'medium',
        showIcon: false,
        action: 'submit', // submit, reset, custom
      },
      size: { width: 150, height: 40 },
      style: {
        backgroundColor: '#3b82f6',
        textColor: '#ffffff',
        borderColor: '#3b82f6',
        borderWidth: 1,
        borderRadius: 6,
      }
    },
  },
  {
    type: 'link',
    label: 'Link',
    icon: Link,
    category: 'action',
    defaultProperties: {
      label: 'Link',
      required: false,
      properties: {
        text: 'Click Here',
        url: 'https://example.com',
        target: '_blank',
        showIcon: true,
      },
      size: { width: 150, height: 30 },
      style: {
        backgroundColor: 'transparent',
        textColor: '#3b82f6',
        borderColor: 'transparent',
        borderWidth: 0,
        borderRadius: 0,
      }
    },
  },
  {
    type: 'submit',
    label: 'Submit Button',
    icon: Send,
    category: 'action',
    defaultProperties: {
      label: 'Submit',
      required: false,
      size: { width: 150, height: 40 },
      style: {
        backgroundColor: '#3b82f6',
        textColor: '#ffffff',
        borderColor: '#3b82f6',
        borderWidth: 1,
        borderRadius: 6,
      },
      properties: {
        variant: 'primary',
        size: 'medium',
        showIcon: true,
      },
    },
  },
];

export const CATEGORIES = {
  input: 'Input Fields',
  selection: 'Selection',
  action: 'Actions',
  advanced: 'Advanced',
} as const;

export const MIN_ELEMENT_SIZE = {
  width: 50,
  height: 30,
};

export const MAX_ELEMENT_SIZE = {
  width: 800,
  height: 600,
};

export const DEFAULT_ELEMENT_POSITION = {
  x: 50,
  y: 50,
};

export const GRID_SIZE = 10;

export const CANVAS_CONFIG = {
  minWidth: 800,
  minHeight: 600,
  backgroundColor: '#ffffff',
  gridColor: '#f3f4f6',
  showGrid: false,
};

export const RESIZE_HANDLE_SIZE = 12;

export const SELECTION_BORDER_COLOR = '#3b82f6';
export const SELECTION_BORDER_WIDTH = 2;

export const VALIDATION_MESSAGES = {
  required: 'This field is required',
  email: 'Please enter a valid email address',
  minLength: 'Minimum length is {value} characters',
  maxLength: 'Maximum length is {value} characters',
  min: 'Minimum value is {value}',
  max: 'Maximum value is {value}',
  pattern: 'Please match the requested format',
};